<script setup>
import { computed, ref } from 'vue'
import { Activity, BarChart3, Check, ChevronDown, Clipboard, FileText, Gauge, LayoutTemplate, MousePointerClick, Search, Smartphone, Target, TriangleAlert, Users } from '@lucide/vue'
import { priorityMeta } from '../../utils/aiRecommendations'

const props = defineProps({ item: { type: Object, required: true }, index: { type: Number, default: 0 } })
const expanded = ref(false), copied = ref(false)
const categoryIcons = { 'Конверсия': Target, 'SEO': Search, 'Контент': FileText, 'Вовлечённость': Activity, 'Производительность': Gauge, 'Мобильная версия': Smartphone, 'Источники трафика': BarChart3, 'Формы и заявки': LayoutTemplate, 'Поведение пользователей': Users, 'Технические ошибки': TriangleAlert, 'Общие рекомендации': MousePointerClick }
const icon = computed(() => categoryIcons[props.item.category] || MousePointerClick)
const hasDetails = computed(() => props.item.details || props.item.evidence.length || props.item.metrics.length)
const copyText = computed(() => [props.item.title, props.item.description, props.item.details, props.item.actions.length ? `Что рекомендуется сделать:\n${props.item.actions.map((item) => `• ${item}`).join('\n')}` : '', props.item.effect ? `Ожидаемый результат:\n${props.item.effect}` : ''].filter(Boolean).join('\n\n'))
async function copy() { try { await navigator.clipboard.writeText(copyText.value); copied.value = true; setTimeout(() => { copied.value = false }, 1800) } catch { copied.value = false } }
</script>
<template>
  <article class="ai-card group relative min-w-0 overflow-hidden rounded-[1.6rem] border border-brand-100 bg-white p-5 shadow-soft transition duration-300 hover:-translate-y-0.5 hover:shadow-[0_22px_55px_rgba(32,40,70,.12)] sm:p-6" :style="{ '--delay': `${Math.min(index, 8) * 45}ms` }">
    <span class="absolute inset-y-0 left-0 w-1" :class="{ 'bg-red-400': item.priority === 'high', 'bg-amber-400': item.priority === 'medium', 'bg-emerald-400': item.priority === 'low', 'bg-slate-300': item.priority === 'neutral' }" />
    <div class="flex min-w-0 items-start gap-3"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-brand-50 text-brand-600"><component :is="icon" :size="21" /></span><div class="min-w-0 flex-1"><div class="flex flex-wrap gap-2"><span class="rounded-full px-2.5 py-1 text-xs font-bold" :class="{ 'bg-red-50 text-red-700': item.priority === 'high', 'bg-amber-50 text-amber-700': item.priority === 'medium', 'bg-emerald-50 text-emerald-700': item.priority === 'low', 'bg-slate-100 text-slate-600': item.priority === 'neutral' }">{{ priorityMeta[item.priority].label }}</span><span class="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-semibold text-brand-700">{{ item.category }}</span></div><h3 class="mt-3 break-words text-lg font-bold leading-snug text-slate-950 sm:text-xl">{{ item.title }}</h3></div><button type="button" class="icon-button shrink-0" :aria-label="copied ? 'Текст скопирован' : 'Скопировать рекомендацию'" :title="copied ? 'Скопировано' : 'Скопировать'" @click="copy"><Check v-if="copied" :size="18" class="text-emerald-600" /><Clipboard v-else :size="18" /></button></div>
    <section v-if="item.description" class="mt-5 rounded-2xl bg-slate-50 p-4"><h4 class="text-xs font-bold uppercase tracking-wide text-slate-500">Почему это важно</h4><p class="mt-2 whitespace-pre-line break-words text-sm leading-6 text-slate-700">{{ item.description }}</p></section>
    <section v-if="item.actions.length" class="mt-5"><h4 class="text-sm font-bold text-slate-900">Что рекомендуется сделать</h4><ul class="mt-3 space-y-2"><li v-for="action in item.actions" :key="action" class="flex min-w-0 gap-2.5 text-sm leading-6 text-slate-700"><Check class="mt-1 shrink-0 text-brand-500" :size="16" /><span class="break-words">{{ action }}</span></li></ul></section>
    <section v-if="item.effect" class="mt-5 rounded-2xl border border-emerald-100 bg-emerald-50/70 p-4"><h4 class="text-xs font-bold uppercase tracking-wide text-emerald-700">Ожидаемый результат</h4><p class="mt-2 break-words text-sm leading-6 text-emerald-950">{{ item.effect }}</p></section>
    <button v-if="hasDetails" type="button" class="mt-5 flex min-h-10 items-center gap-2 rounded-xl px-1 text-sm font-semibold text-brand-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500" :aria-expanded="expanded" @click="expanded = !expanded"><ChevronDown :size="17" class="transition" :class="expanded && 'rotate-180'" />{{ expanded ? 'Скрыть подробности' : 'Показать подробности' }}</button>
    <div v-if="expanded" class="mt-3 grid gap-4 border-t border-slate-100 pt-4 sm:grid-cols-2"><div v-if="item.details"><h4 class="text-xs font-bold uppercase text-slate-500">Подробная рекомендация</h4><p class="mt-2 whitespace-pre-line break-words text-sm leading-6 text-slate-700">{{ item.details }}</p></div><div v-if="item.evidence.length"><h4 class="text-xs font-bold uppercase text-slate-500">Основание рекомендации</h4><ul class="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-700"><li v-for="value in item.evidence" :key="value">{{ value }}</li></ul></div><div v-if="item.metrics.length"><h4 class="text-xs font-bold uppercase text-slate-500">Связанные показатели</h4><div class="mt-2 flex flex-wrap gap-2"><span v-for="value in item.metrics" :key="value" class="rounded-lg bg-slate-100 px-2.5 py-1 text-xs text-slate-700">{{ value }}</span></div></div></div>
  </article>
</template>

