# Generated by Django 4.2.16 on 2026-07-03 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст новости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликована')),
                ('is_important', models.BooleanField(db_index=True, default=False, verbose_name='Важная')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_news_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость TrackNode',
                'verbose_name_plural': 'Новости TrackNode',
                'ordering': ('-is_important', '-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='UserNewsRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Прочитано')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='notifications.dashboardnews', verbose_name='Новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_reads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прочтение новости',
                'verbose_name_plural': 'Прочтения новостей',
                'ordering': ('-read_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='usernewsread',
            constraint=models.UniqueConstraint(fields=('user', 'news'), name='unique_user_news_read'),
        ),
        migrations.AddIndex(
            model_name='dashboardnews',
            index=models.Index(fields=['is_published', '-published_at'], name='news_publish_idx'),
        ),
    ]
