# Generated by Django 4.2.16 on 2026-06-24 14:53

import competitor_analysis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0006_alter_client_options_alter_client_api_key_and_more'),
        ('sites', '0013_add_novaya_konakova_section_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitors', models.JSONField(blank=True, default=list, verbose_name='Домены конкурентов')),
                ('status', models.CharField(choices=[('pending', 'Ожидает запуска'), ('running', 'Выполняется'), ('done', 'Готово'), ('error', 'Ошибка')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='Результаты анализа')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=competitor_analysis.models.competitor_analysis_pdf_upload_to, verbose_name='PDF-отчёт')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery task ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_analyses', to='clients.client', verbose_name='Клиент')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_analyses', to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Анализ конкурентов',
                'verbose_name_plural': 'Анализы конкурентов',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['site', 'status', 'created_at'], name='competitor__site_id_2ea17b_idx'), models.Index(fields=['client', 'created_at'], name='competitor__client__b866a3_idx')],
            },
        ),
    ]
