# Generated by Django 4.2.16 on 2026-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitoranalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает запуска'), ('running', 'Выполняется'), ('completed', 'Готово'), ('failed', 'Ошибка'), ('canceled', 'Остановлен'), ('done', 'Готово'), ('error', 'Ошибка')], db_index=True, default='pending', max_length=16, verbose_name='Статус'),
        ),
    ]
