# Generated by Django 4.2.16 on 2026-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor_analysis', '0002_alter_competitoranalysis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitoranalysis',
            name='competitor_domain',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Домен конкурента'),
        ),
        migrations.AddField(
            model_name='competitoranalysis',
            name='user_domain',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Домен пользователя'),
        ),
    ]
