<script setup>
import { computed, onMounted, ref } from 'vue'
import { RefreshCw } from '@lucide/vue'
import PlatformPeriodFilter from '../../components/platform/PlatformPeriodFilter.vue'
import { getPlatformAnalytics } from '../../api/platform'
const period = ref({ period: '30d' }), data = ref(null), loading = ref(true), error = ref('')
const labels = { visits: 'Посещения', unique_visitors: 'Уникальные посетители', page_views: 'Просмотры', leads: 'Заявки', events: 'События', conversion: 'Конверсия, %', errors: 'Ошибки' }
const maxVisits = computed(() => Math.max(...(data.value?.daily || []).map((row) => row.visits), 1))
async function load() { loading.value = true; try { data.value = (await getPlatformAnalytics(period.value)).data; error.value = '' } catch (e) { error.value = e.response?.data?.detail || 'Не удалось загрузить аналитику.' } finally { loading.value = false } }
onMounted(load)
</script>
<template><section class="space-y-4"><div class="flex flex-wrap items-end justify-between gap-3 rounded-3xl bg-slate-900 p-4 text-white"><div><h2 class="text-lg font-semibold">Общая аналитика</h2><p class="text-xs text-slate-400">Динамика по всем сайтам</p></div><PlatformPeriodFilter v-model="period" @change="load" /></div><div v-if="error" class="rounded-2xl bg-red-50 p-4 text-red-800">{{ error }}</div><div v-if="loading" class="rounded-3xl bg-white p-12 text-center"><RefreshCw class="inline animate-spin" /></div><template v-else-if="data"><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><article v-for="(value,key) in data.totals" :key="key" class="rounded-2xl bg-white p-4 shadow-soft"><p class="text-xs text-slate-500">{{ labels[key] }}</p><strong class="mt-2 block text-2xl">{{ value }}</strong></article></div><div class="rounded-3xl bg-white p-5 shadow-soft"><h3 class="font-semibold">Посещения по дням</h3><div class="mt-6 flex h-52 items-end gap-1 overflow-x-auto"><div v-for="row in data.daily" :key="row.day" class="group flex min-w-6 flex-1 flex-col items-center justify-end"><span class="mb-1 hidden text-[10px] group-hover:block">{{ row.visits }}</span><div class="w-full rounded-t bg-gradient-to-t from-violet-700 to-violet-400" :style="{ height: `${Math.max(3, row.visits / maxVisits * 180)}px` }" :title="`${row.day}: ${row.visits}`"></div></div></div></div><div class="grid gap-4 lg:grid-cols-2"><div class="rounded-3xl bg-white p-5 shadow-soft"><h3 class="font-semibold">Популярные сайты</h3><div v-for="site in data.popular_sites" :key="site.site_id" class="mt-3 flex justify-between text-sm"><RouterLink :to="`/platform/sites/${site.site_id}`" class="text-violet-700">{{ site.site__name }}</RouterLink><b>{{ site.visits }}</b></div></div><div class="rounded-3xl bg-white p-5 shadow-soft"><h3 class="font-semibold">Сайты без посещений</h3><div v-for="site in data.sites_without_traffic" :key="site.id" class="mt-3 text-sm"><RouterLink :to="`/platform/sites/${site.id}`" class="text-violet-700">{{ site.name }}</RouterLink></div></div></div></template></section></template>

