# Generated by Django 4.2.16 on 2026-07-10 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0015_rebrand_a_meditation_public_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('remote_job_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('recommendation_type', models.CharField(choices=[('seo', 'SEO'), ('conversion', 'Конверсия'), ('combined', 'Комплексный')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('processing', 'Выполняется'), ('completed', 'Готово'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], db_index=True, default='queued', max_length=20)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('input_snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('poll_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendation_jobs', to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'site', 'status'], name='ai_recommen_user_id_92135c_idx')],
            },
        ),
    ]
