# Generated by Django 4.2.16 on 2026-07-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendationjob',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airecommendationjob',
            name='openai_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='airecommendationjob',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airecommendationjob',
            name='platform_hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airecommendationjob',
            name='platform_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airecommendationjob',
            name='prompt_version',
            field=models.CharField(default='business-owner-v1', max_length=50),
        ),
    ]
