# Generated by Django 5.2.11 on 2026-02-20 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_scheduleday_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка через контакты',
                'verbose_name_plural': 'Заявки через контакты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayScenarioRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date', models.DateField(verbose_name='Дата')),
                ('guests', models.PositiveIntegerField(verbose_name='Гостей')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка на сценарий дня',
                'verbose_name_plural': 'Заявки на сценарий дня',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.CharField(blank=True, max_length=255, verbose_name='Тариф')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='core.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заявка на услугу',
                'verbose_name_plural': 'Заявки на услуги',
                'ordering': ['-created_at'],
            },
        ),
    ]
