# Generated by Django 4.2.16 on 2026-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_visit_bot_reason'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visit', 'type', 'timestamp'], name='tracker_eve_visit_i_1394c5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type', 'timestamp'], name='tracker_eve_type_ec08ac_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['visit', 'timestamp'], name='tracker_pag_visit_i_f059d8_idx'),
        ),
    ]
