# Generated by Django 4.2.16 on 2026-03-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_repair_legacy_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagegalleryimage",
            name="caption",
            field=models.CharField(
                blank=True,
                help_text="Необязательно. Короткая подпись к изображению.",
                max_length=255,
                verbose_name="Подпись",
            ),
        ),
        migrations.AddField(
            model_name="pagegalleryimage",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Снимите галочку, чтобы временно скрыть изображение.",
                verbose_name="Показывать на сайте",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Чем меньше число, тем выше элемент отображается на сайте.",
                verbose_name="Порядок сортировки",
            ),
        ),
        migrations.AlterField(
            model_name="pagegalleryimage",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Чем меньше число, тем выше элемент отображается на сайте.",
                verbose_name="Порядок сортировки",
            ),
        ),
        migrations.AlterField(
            model_name="pagesection",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Чем меньше число, тем выше элемент отображается на сайте.",
                verbose_name="Порядок сортировки",
            ),
        ),
    ]
