# Generated by Django 5.2.11 on 2026-03-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_pagegalleryimage_caption_pagegalleryimage_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagegalleryimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='pagegalleryimage',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='pagegalleryimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
