# Generated by Django 5.2.11 on 2026-02-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_scheduleevent_image"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE core_service
                    ADD COLUMN IF NOT EXISTS image VARCHAR(100) NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE core_service
                    DROP COLUMN IF EXISTS image;
                    """,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="service",
                    name="image",
                    field=models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Изображение карточки",
                    ),
                )
            ],
        ),
    ]
