# Generated by Django 5.2.11 on 2026-02-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_repair_schedule_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleday',
            options={'ordering': ['date'], 'verbose_name': 'День расписания', 'verbose_name_plural': 'Дни расписания'},
        ),
        migrations.AlterModelOptions(
            name='scheduleevent',
            options={'ordering': ['time_start', 'order'], 'verbose_name': 'Событие расписания', 'verbose_name_plural': 'События расписания'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
