# Generated by Django 5.2.11 on 2026-03-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_scheduleday_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="services/gallery/", verbose_name="Изображение")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение услуги",
                "verbose_name_plural": "Галерея услуг",
                "ordering": ["order", "id"],
            },
        ),
    ]
