# Generated by Django 4.2.16 on 2026-03-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_scheduleday_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contacts_title",
                    models.CharField(default="Контакты", max_length=120, verbose_name="Заголовок блока контактов"),
                ),
                (
                    "phone_label",
                    models.CharField(default="Телефон", max_length=120, verbose_name="Подпись телефона"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="+7 (985) 200-63-22",
                        help_text="Формат отображения в футере, например: +7 (999) 123-45-67.",
                        max_length=255,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email_label",
                    models.CharField(default="E-mail", max_length=120, verbose_name="Подпись e-mail"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="elizaveta-struchkova@yandex.ru",
                        help_text="Основной адрес для связи, который будет показан в футере.",
                        max_length=254,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "address_label",
                    models.CharField(default="Адрес", max_length=120, verbose_name="Подпись адреса"),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        default="Тверская область, Конаковский район, природный кластер «Новое Конаково».",
                        help_text="Полный адрес, который нужно показать в футере.",
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "socials_title",
                    models.CharField(default="Социальные сети", max_length=120, verbose_name="Заголовок блока соцсетей"),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="© New Konakovo. Все права защищены.",
                        help_text="Текст в нижней части футера. При необходимости используйте {year} для подстановки текущего года.",
                        max_length=255,
                        verbose_name="Текст копирайта",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Настройки футера",
                "verbose_name_plural": "Настройки футера",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["order", "id"], "verbose_name": "Услуга", "verbose_name_plural": "Услуги"},
        ),
        migrations.AlterModelOptions(
            name="tariff",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Тариф услуги",
                "verbose_name_plural": "Тарифы услуг",
            },
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_category",
            field=models.BooleanField(default=False, verbose_name="Категория"),
        ),
        migrations.AlterField(
            model_name="service",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Чем меньше число, тем выше элемент отображается на сайте.",
                verbose_name="Порядок сортировки",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.service",
                verbose_name="Родительская услуга",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="duration",
            field=models.CharField(blank=True, max_length=255, verbose_name="Длительность"),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Чем меньше число, тем выше элемент отображается на сайте.",
                verbose_name="Порядок сортировки",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="price",
            field=models.IntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tariffs",
                to="core.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="slug",
            field=models.SlugField(verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название тарифа"),
        ),
        migrations.CreateModel(
            name="ServiceGalleryImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="services/gallery/", verbose_name="Изображение")),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Необязательно. Короткая подпись к фото в галерее.",
                        max_length=255,
                        verbose_name="Подпись",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше элемент отображается на сайте.",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы временно скрыть изображение.",
                        verbose_name="Показывать на сайте",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото галереи услуги",
                "verbose_name_plural": "Галерея услуг",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FooterSocialLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Например: Telegram, VK, WhatsApp.",
                        max_length=120,
                        verbose_name="Название",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Полная ссылка, например https://t.me/username.",
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше элемент отображается на сайте.",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать в футере")),
                (
                    "footer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="core.footersettings",
                        verbose_name="Настройки футера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка соцсети в футере",
                "verbose_name_plural": "Ссылки соцсетей в футере",
                "ordering": ["order", "id"],
            },
        ),
    ]
