# Generated by Django 5.2.11 on 2026-03-22 00:00

from django.db import migrations, models


def seed_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    if SiteSettings.objects.exists():
        return

    SiteSettings.objects.create(
        phone="+7 (985) 200-63-22",
        email="elizaveta-struchkova@yandex.ru",
        telegram_url="https://t.me/novoe_konakovo",
        telegram_username="@novoe_konakovo",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_serviceimage_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(blank=True, default="+7 (985) 200-63-22", max_length=255, verbose_name="Телефон")),
                ("email", models.EmailField(blank=True, default="elizaveta-struchkova@yandex.ru", max_length=254, verbose_name="Email")),
                ("telegram_url", models.URLField(blank=True, default="https://t.me/novoe_konakovo", verbose_name="Ссылка Telegram")),
                ("telegram_username", models.CharField(blank=True, default="@novoe_konakovo", max_length=255, verbose_name="Подпись Telegram")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.RunPython(seed_site_settings, migrations.RunPython.noop),
    ]
