# Generated by Django 5.2.11 on 2026-03-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_footer_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default='Тверская область, Конаковский район, природный кластер «Новое Конаково».', verbose_name='Адрес'),
        ),
    ]
