# Generated by Django 5.2.11 on 2026-03-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_footersettings_alter_service_options_and_more'),
        ('core', '0013_sitesettings_footer_contacts'),
    ]

    operations = [
    ]
