# Generated by Django 5.2.11 on 2026-03-22 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20260322_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersociallink',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='servicegalleryimage',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='duration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='core.service'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='FooterSettings',
        ),
        migrations.DeleteModel(
            name='FooterSocialLink',
        ),
        migrations.DeleteModel(
            name='ServiceGalleryImage',
        ),
    ]
