# Generated by Django 5.2.11 on 2026-03-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_address'),
        ('core', '0015_remove_footersociallink_footer_and_more'),
    ]

    operations = [
    ]
